"use client";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, BarChart3, BookOpen, BrainCircuit, CheckCircle2, Clock3, Target, TrendingUp } from "lucide-react";

const subjects=[["Modern History",78,"Strong foundation"],["Polity",64,"Needs revision"],["Economy",56,"Focus area"],["Environment",71,"Improving"],["Geography",69,"Improving"]];
const tests=[["Modern History • Prelims",7.34,"82%","Today"],["Polity • Prelims",6.01,"68%","Yesterday"],["Economy • Prelims",7.98,"76%","18 Sep"],["GS-II • Mains",6.5,"65%","17 Sep"]];

export default function Performance(){
 return <main className="min-h-screen bg-[#07090d] px-5 text-white">
  <header className="mx-auto flex h-20 max-w-6xl items-center justify-between"><Link href="/dashboard" className="flex items-center gap-2 text-sm text-white/50"><ArrowLeft size={16}/> UPSCora</Link><span className="text-sm font-semibold">Performance</span></header>
  <div className="mx-auto max-w-6xl py-5">
   <div><p className="text-xs uppercase tracking-[.2em] text-white/35">Your preparation</p><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Know exactly where you stand.</h1><p className="mt-3 text-sm text-white/45">Use your test history to identify weak areas and decide what to revise next.</p></div>
   <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<Target size={16}/>} label="Overall accuracy" value="69.8%" trend="+4.2%"/><Metric icon={<BarChart3 size={16}/>} label="Prelims average" value="72.4" trend="+3.1"/><Metric icon={<BookOpen size={16}/>} label="Tests completed" value="18" trend="+6 this month"/><Metric icon={<Clock3 size={16}/>} label="Study sessions" value="32" trend="+18%"/></div>

   <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]">
    <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Accuracy trend</p><p className="mt-1 text-xs text-white/35">Last 7 practice sessions</p></div><TrendingUp size={18} className="text-emerald-300"/></div><div className="mt-7 flex h-48 items-end gap-3 border-b border-white/8">{[52,58,55,64,61,73,70].map((v,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full max-w-12 rounded-t-xl bg-white/20" style={{height:`${v*2.1}px`}}/><span className="text-[10px] text-white/25">S{i+1}</span></div>)}</div></section>
    <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><p className="text-sm font-semibold">AI Mentor focus</p><div className="mt-5 rounded-2xl border border-amber-300/10 bg-amber-300/[0.03] p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white text-black"><BrainCircuit size={17}/></span><p className="text-sm font-medium">Revise Economy first</p></div><p className="mt-4 text-sm leading-6 text-white/45">Your Economy accuracy is currently below your overall average. Focus on inflation, monetary policy and fiscal policy before your next full-length test.</p><Link href="/tests" className="mt-5 inline-flex items-center gap-2 text-sm">Practice now <ArrowUpRight size={14}/></Link></div></section>
   </div>

   <div className="mt-5 grid gap-5 lg:grid-cols-2">
    <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Subject performance</p><p className="mt-1 text-xs text-white/35">Accuracy by subject</p></div><BarChart3 size={18} className="text-white/30"/></div><div className="mt-6 space-y-5">{subjects.map(([name,val,status])=><div key={name}><div className="flex justify-between text-xs"><span>{name}</span><span className="text-white/45">{val}%</span></div><div className="mt-2 h-2 rounded-full bg-white/8"><div className="h-2 rounded-full bg-white/60" style={{width:`${val}%`}}/></div><p className="mt-1 text-[11px] text-white/30">{status}</p></div>)}</div></section>
    <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><p className="text-sm font-semibold">Weak topics to revise</p><p className="mt-1 text-xs text-white/35">Based on recent mistakes</p><div className="mt-5 space-y-3">{["Monetary Policy","Constitutional Bodies","Ecological Succession","Land Revenue Systems","Parliamentary Procedures"].map((x,i)=><div key={x} className="flex items-center justify-between rounded-2xl border border-white/8 p-4"><div><p className="text-sm">{x}</p><p className="mt-1 text-xs text-white/30">{i<2?"High priority":"Revision recommended"}</p></div><span className="text-xs text-white/35">{i+2} mistakes</span></div>)}</div></section>
   </div>

   <section className="mt-5 rounded-3xl border border-white/10 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Recent tests</p><p className="mt-1 text-xs text-white/35">Your latest practice activity</p></div><Link href="/tests" className="text-xs text-white/45">View tests →</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-white/8 text-xs text-white/30"><th className="pb-3">Test</th><th className="pb-3">Score</th><th className="pb-3">Accuracy</th><th className="pb-3">Date</th></tr></thead><tbody>{tests.map(t=><tr key={t[0]} className="border-b border-white/6"><td className="py-4">{t[0]}</td><td className="py-4 text-white/70">{t[1]}</td><td className="py-4 text-emerald-300">{t[2]}</td><td className="py-4 text-white/35">{t[3]}</td></tr>)}</tbody></table></div></section>

   <section className="mt-5 rounded-3xl border border-white/10 bg-white/[0.025] p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-white/10"><CheckCircle2 size={17}/></span><div><p className="text-sm font-semibold">Suggested revision plan</p><p className="text-xs text-white/35">Generated from your current performance</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-3"><Plan day="Today" title="Economy" text="Inflation + Monetary Policy • 45 min"/><Plan day="Tomorrow" title="Polity" text="Constitutional Bodies • 40 min"/><Plan day="Next" title="Modern History" text="Land Revenue Systems • 35 min"/></div></section>
  </div>
 </main>
}
function Metric({icon,label,value,trend}:{icon:React.ReactNode,label:string,value:string,trend:string}){return <div className="rounded-3xl border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-xs text-white/35">{icon}{label}</div><p className="mt-3 text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-emerald-300">{trend}</p></div>}
function Plan({day,title,text}:{day:string,title:string,text:string}){return <div className="rounded-2xl border border-white/8 p-4"><span className="text-[10px] uppercase tracking-[.18em] text-white/30">{day}</span><p className="mt-2 text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-5 text-white/40">{text}</p></div>}
